# src/OC/PlatformBundle/Resources/config/routing.yml
oc_platform_home:
   path:      index/{page}
   defaults:  { _controller: OCPlatformBundle:Advert:index, page: 1  }

oc_platform_view:
   path:      /advert/{id}
   defaults:  { _controller: OCPlatformBundle:Advert:view }

oc_platform_add:
    path:      /add
    defaults:  { _controller: OCPlatformBundle:Advert:add }

oc_platform_edit:
    path:      /edit/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:edit }

oc_platform_delete:
    path:      /delete/{id}
    defaults:  { _controller: OCPlatformBundle:Advert:delete }

oc_platform_listit:
    path:      /listit
    defaults:  { _controller: OCPlatformBundle:Advert:listit }

oc_platform_test:
    path:      /test
    defaults:  { _controller: OCPlatformBundle:Advert:test }
