services:
   # oc_platform.antispam:
   #     class: OC\PlatformBundle\Antispam\OCAntispam
   #     arguments: [@mailer, 50, %locale%]
   oc_platform.doctrine.notification:
       class: OC\PlatformBundle\DoctrineListener\ApplicationNotification
       arguments: [@mailer]
       tags:
           - { name: doctrine.event_listener, event: postPersist }
   oc_platform.validator.antiflood:
       class: OC\PlatformBundle\Validator\AntifloodValidator
       arguments: [@request_stack, @doctrine.orm.entity_manager]
       tags:
        - { name: validator.constraint_validator, alias: oc_platform_antiflood }
